console.log(Int8Array.BYTES_PER_ELEMENT);
console.log(Uint8Array.BYTES_PER_ELEMENT);
console.log(Uint8ClampedArray.BYTES_PER_ELEMENT);
console.log(Int16Array.BYTES_PER_ELEMENT);
console.log(Uint16Array.BYTES_PER_ELEMENT);
console.log(Int32Array.BYTES_PER_ELEMENT);
console.log(Uint32Array.BYTES_PER_ELEMENT);
console.log(Float32Array.BYTES_PER_ELEMENT);
console.log(Float64Array.BYTES_PER_ELEMENT);
